const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 3000;
const MIME_TYPES = {
    '.html': 'text/html',
    '.js': 'text/javascript',
    '.css': 'text/css',
    '.json': 'application/json',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
};

const server = http.createServer((req, res) => {
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);

    // Handle API Save Request
    if (req.method === 'POST' && req.url === '/api/save_locations.php') {
        let body = '';
        req.on('data', chunk => {
            body += chunk.toString();
        });
        req.on('end', () => {
            try {
                const data = JSON.parse(body);
                const locations = data.locations;

                // Create the JS content
                const fileContent = `// Vila Abandonada - Game Map Data
// Generated by Location Editor (Local Server)
// Last update: ${new Date().toISOString()}

const GAME_MAP = ${JSON.stringify(locations, null, 4)};

// Helper functions
function getLocation(locationId) {
    return GAME_MAP[locationId];
}

function getUnlockedLocations() {
    return Object.values(GAME_MAP).filter(loc => loc.unlocked);
}

// Export for use in game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAME_MAP, getLocation, getUnlockedLocations };
}`;

                // Write to js/map.js
                const mapPath = path.join(__dirname, 'js', 'map.js');
                fs.writeFileSync(mapPath, fileContent);

                console.log('✅ Saved successfully to js/map.js');

                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({
                    success: true,
                    message: 'Saved successfully to local file',
                    data: {
                        locations: Object.keys(locations).length,
                        hotspots: 0 // Not counting for now
                    }
                }));
            } catch (error) {
                console.error('❌ Error saving:', error);
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: false, message: error.message }));
            }
        });
        return;
    }

    // Handle Static Files
    let filePath = '.' + req.url;
    if (filePath === './') {
        filePath = './location-editor-db.html';
    }

    // Remove query strings
    filePath = filePath.split('?')[0];

    const extname = path.extname(filePath);
    let contentType = MIME_TYPES[extname] || 'application/octet-stream';

    fs.readFile(filePath, (error, content) => {
        if (error) {
            if (error.code === 'ENOENT') {
                fs.readFile('./404.html', (error, content) => {
                    res.writeHead(404, { 'Content-Type': 'text/html' });
                    res.end(content || '404 Not Found', 'utf-8');
                });
            } else {
                res.writeHead(500);
                res.end('Sorry, check with the site admin for error: ' + error.code + ' ..\n');
            }
        } else {
            res.writeHead(200, { 'Content-Type': contentType });
            res.end(content, 'utf-8');
        }
    });
});

server.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}/`);
    console.log(`Open http://localhost:${PORT}/location-editor-db.html to edit`);
});
